### ISSUE TITLE
Your Finances

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-application-DEPRECATED#32]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

**[Notion Link](https://www.notion.so/lofftapp/Your-Finances-0e84d662a87a456a870a6e9ef077eea9)**

---

### Feature experience

- As a `User` I can view my expenses with other users
- As a `User` I can choose to send money to other user.
- As a `User` I can request money from another User.
- As a `User` I can view data within a graph showing expenses day by day or weekly.

### Todo

- [x]  Connect to the API and collect relevant expenses associated with the use.
- [x]  Calculate the sum to pay or some owed in total.
- [ ]  Build a graph showing the monthly/weekly/yearly financial changes

### Design
_Refer to Figma for latest designs_
<img width="172" alt="Screenshot 2021-12-09 at 17 07 59" src="https://user-images.githubusercontent.com/5392107/145432559-8c997dcd-3b06-4836-84cc-f10fa0fd178a.png">
<img width="175" alt="Screenshot 2021-12-09 at 17 08 10" src="https://user-images.githubusercontent.com/5392107/145432598-ad5a90de-ce4f-4802-b9fc-dd8c6af517bc.png">
