### ISSUE TITLE
Request Payment

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-application-DEPRECATED#38]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

**[Notion Link](https://www.notion.so/lofftapp/Request-Payment-fd0ef91ad1d74df9ba12ce781c381579)**

---

### Feature experience

- As a `User` I can add a new payment
- As a `User` I can request individual payments.
- As a `User` I can split the requests evenly or request individual amounts from each user.
- As a `User` I can set if the payments/pot is recurring or closes once the debt is paid.

### To-do

- [ ]  Create a request form for payments
- [ ]  Allow for the total amount to be added (Specify € initially)
- [ ]  Get all members of the WG in a list to choose from to add to the payment.

### Design
<img width="637" alt="Screenshot 2021-12-23 at 15 05 18" src="https://user-images.githubusercontent.com/5392107/147258288-a21edad2-2e7d-47ef-a7a7-910bd182bb0d.png">

**Comment by jhibbeard89** [comment]
@valentinLW You let me know when you're done with this I think the page I am working on feeds to this page.

**Comment by jhibbeard89** [comment]
@valentinLW I am going to update this Issue with a few things.

**Comment by jhibbeard89** [comment]
## Closed issue
This issue has now been closed as the Repo is deprecated, a new issue is located on the new repo at https://github.com/LofftApp/lofft-mobile-app/issues/19
