### ISSUE TITLE
T-toggle_pill_button_feature

### ISSUE THREAD

**Issue by AdamTomczyk** [LofftApp/lofft-mobile-application-DEPRECATED#43]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

**[Notion Link](https://www.notion.so/lofftapp/aee7dc5e05e644a88521ee91e01a79a0?v=45b60a4d8a744d0ea17df8c98de771b3&p=4d51c79ca1f943d7adc1734996a27376)**

---

## Feature description
A toggle buttonpill for the mobile application to toggle between views

### Feature experience

As a `visitor` I can change my dashboard depending on the button

---

### Todo

- [ ] Create a universal toggle logic as a hook
- [ ] Create toggle logic with state as a component
- [ ] Implement Component on the Screen

### Design

<img width="412" alt="Button" src="https://user-images.githubusercontent.com/86358155/147392778-6aa61710-315a-4a7b-91aa-04d59bf0f444.png">
