### ISSUE TITLE
Chart JS and Toggle Fix 

### ISSUE THREAD

**Issue by AdamTomczyk** [LofftApp/lofft-mobile-application-DEPRECATED#46]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

**[Notion Link]()**

---

## Feature description

Futher enchangment of Dashboard feautres such as toggle and Chart 

### Feature experience

- I can see my spending history
- I can visualize my spending by different intervals via spending

### Todo

- [x] Intergrate Chart Js
- [x] Fix Default Toggle State
- [x] History/Dashboard Toggle and correspoing conditional

### Design
![Iphone13](https://user-images.githubusercontent.com/86358155/148199964-e53c6cc4-19bd-46d8-9859-c68cabefa1b2.png)

**Comment by jhibbeard89** [comment]
This task has been completed and will be closed.
